build:
  ami:
    image: localhost:5000/plataforma/condor-estudiantes-image:master-23300b3-0
    commands:
      - rm -rf target
      - mkdir -pv target
      - cp -rv /artifacts/* target/
      - cp -fv plantillas/* target/

deploy:
  terraform:
    # plan: true
    remote:
      backend: S3
      config:
        bucket: $$OAS_REPO
        key: terraform/condor-estudiantes-stacks.$$BRANCH.tfstate
        region: us-east-1
        access_key: $$AWS_ACCESS_KEY_ID
        secret_key: $$AWS_SECRET_ACCESS_KEY
    vars:
      aws_region: us-east-1
      aws_secret_key: $$AWS_SECRET_ACCESS_KEY
      aws_access_key: $$AWS_ACCESS_KEY_ID
      branch: $$BRANCH
      commit: "$${COMMIT:0:7}"
      build_number: "$$BUILD_NUMBER"
      instance_type: t2.micro
      subnet_1: subnet-f712f4af
      subnet_2: subnet-b3eafa98
    root_dir: target
